title: "Kahina Saidi – Tests Manuels, Automatisation et Qualité Logicielle"
description: "Passionnée par la qualité logicielle et les tests manuels. Expert en Cypress et ISTQB."
image: "./img/photo.png"
theme: minima  
